### ISSUE TITLE
Problem in Windows

### ISSUE THREAD

**Issue by gshilin** [proxylocal/proxylocal-gem#1]
c:/Ruby/lib/ruby/gems/1.8/gems/proxylocal-0.2.2/lib/client.rb:28:in `trap': unsupported signal SIGCLD (ArgumentError)
from c:/Ruby/lib/ruby/gems/1.8/gems/proxylocal-0.2.2/lib/client.rb:28:in`run'
from c:/Ruby/lib/ruby/gems/1.8/gems/proxylocal-0.2.2/bin/proxylocal:71
from c:/Ruby/bin/proxylocal:19:in `load'
from c:/Ruby/bin/proxylocal:19

**Comment by lest** [comment]
fixed in version 0.2.4
