### ISSUE TITLE
A connection has been terminated

### ISSUE THREAD

**Issue by msorc** [proxylocal/proxylocal-gem#2]
$ proxylocal 3000
A connection has been terminated

What is that about?

**Comment by lest** [comment]
Could you run

```
proxylocal -v 3000
```

and post output?

**Comment by msorc** [comment]
proxylocal -v 3000  
I, [2010-12-20T11:17:04.848101 #4421]  INFO -- : Run with options {:server_port=>"8282", :local_port=>"3000", :verbose=>true, :tls=>false, :version=>"0.2.2", :server_host=>"proxylocal.com"}  
A connection has been terminated 

Most probably we have a closed port to connect to proxylocal.com at our corporate firewall.

**Comment by lest** [comment]
It uses port 8282 to communicate with server, so this port shouldn't be closed on firewall for outgoing connections.

**Comment by davidsilvasmith** [comment]
The site is for sale. I don't think this software works anymore.

http://www.proxylocal.com/

**Comment by manojk-ror** [comment]
We can use **[ngrok](https://ngrok.com/download)** for creating local proxy and access to same/another network. We should need to follow below steps -
1. Download from below link as per your requirement
https://ngrok.com/download
2. Unzip it
$ unzip /path/to/ngrok.zip
3. Run command on terminal (I am assuming your application is already running on 3000 port ) -
$ ./ngrok http 3000
4. When you run above command then able to see new ngrok console screen -
Copy Forwarding url and use it as proxy URL.
